<a href="https://colab.research.google.com/github/AbdulRauf96/Python-Pratice/blob/main/Numpy_and_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy and Linear Algebra

This notebook contains explains of NumPy functions and matrix calculations that can be performed using this package

#### Basic NumPy Array and Matrix creation

In [ ]:
import numpy as np

In [ ]:
#Create an array with specific data type
np.array([1,2,3], dtype=int)

array([1, 2, 3])

In [ ]:
#Create an array with boolean
np.array([1,0,1,0], dtype=bool)

array([ True, False,  True, False])

In [ ]:
#Create an array with specific range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Specify the range and how big the step is
np.arange(1,100, 5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [ ]:
#Create an array in specific range with specific number of elements
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### Matrix

This section we will create a:

1. an empty/zeros/ones matrix
2. an identity matrix
3. a diagonal matrix
4. a random matrix with the specified range, dimension, and datatype
5. a copy of a matrix with the same dimension but different elements

In [ ]:
#Create an empty matrix
np.empty((3,3))

array([[0.11111111, 0.22222222, 0.33333333],
       [0.44444444, 0.55555556, 0.66666667],
       [0.77777778, 0.88888889, 1.        ]])

In [ ]:
#Create an array with 0 elements
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#Create the matrix filled with specified elements
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#Create an identity matrix with dimension 3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Create a diagonal matrix with diagonal elements specified in the array x
x = [1,2,3]
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
#Create a matrix with random elements between 0 and 1
np.random.random((3,3))

array([[0.29934842, 0.13350963, 0.50485988],
       [0.66862584, 0.9818822 , 0.42632167],
       [0.69855038, 0.3842606 , 0.15271532]])

In [ ]:
#Create a matrix with random float elements with a specific range
np.random.normal(0, 10, (3,3))

array([[  2.68576037,   6.36184279,   6.2559436 ],
       [  3.72237516,  20.25639523,   8.86785008],
       [  2.94864183,  -2.59759294, -14.78966953]])

In [ ]:
#Create a matrix with random integer elements with a specific range
np.random.randint(0,10, (3,3))

array([[2, 4, 0],
       [3, 4, 3],
       [1, 7, 2]])

In [ ]:
#Create the matrix with the same dimension but different elements
A = np.zeros((10,10))
B = np.full_like(A,fill_value = 5)
B

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

### Operations on matrices

This section we will create a:

1. Perform element-wise multiplication and matrix multiplication
2. Find the transpose of a matrix (an operator that switches the rows and 3. columns)
3. Find the trace of a matrix (the sum of the diagonal elements)
4. Reshape the matrix
5. Find the slice of a matrix with boolean arrays

In [ ]:
B = np.array([[1, 3, 4], [3, 2, 1]], dtype= float)
A = np.array([[4,5,6],[7,8,9]], dtype=float)

display(A)
B * A
B + A

array([[4., 5., 6.],
       [7., 8., 9.]])

array([[ 5.,  8., 10.],
       [10., 10., 10.]])

In [ ]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float); print(C)
D = np.array([[4],[5],[6]], dtype=float); print(D)
display(A@ C)
np.dot(A,C)
# C.shape

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[4.]
 [5.]
 [6.]]


array([[ 66.,  81.,  96.],
       [102., 126., 150.]])

array([[ 66.,  81.,  96.],
       [102., 126., 150.]])

In [ ]:
#Find the transpose of a matrix
#Transpose: Columns become rows and rows become columns
A.T

array([[4., 7.],
       [5., 8.],
       [6., 9.]])

In [ ]:
#reshape the array
np.arange(10).reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
#Return the sum along the diagonals of the array
np.trace(A)

12.0

In [ ]:
# a.T * y (1xn * nx1)
a = np.arange(5); display(a)
b = np.arange(5); display(b)


#this returns a scaler
np.dot(a,b)

array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

30

In [ ]:
# a * y.T  (nx1 * 1*n)
#this returns a matrix nxn
np.outer(a,b)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [ ]:
#Use boolean to return a specific row
A[[True, False],[True,False,True]]

array([4., 6.])

In [ ]:
#Add a row
np.append(A, [[4,7,9]], axis=0)

#Add a column

np.append(A, [[6],[1]],axis=1)

array([[4., 5., 6., 6.],
       [7., 8., 9., 1.]])

In [ ]:
#function to select certain value
print(A)
A[[0],[2]]

def select_mtrx(mtrx,row,column):
  x = mtrx[[row],column]
  return x

select_mtrx(A,0,1)

[[4. 5. 6.]
 [7. 8. 9.]]


array([5.])

### Linear Algebra

This section shows us how to:

1. Solve the system of linear equations
2. Find the inverse of a matrix
3. Find matrix norm
4. Compute Single Value Decomposition and eigenvalues

In [ ]:
#Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8:

a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

In [ ]:
#Compute the inverse of a matrix
np.linalg.pinv(A)

#Manual calculation for inverse of a matrix
#Inverse of A is A_1 only when AA_1 = I where
I = np.eye(3,3); print(I)
print(A) 


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
#Return matrix norm
np.linalg.norm(A)

16.46207763315433

In [ ]:
#Single Value Decomposition
# Link to understand Singular Value Decomposition: https://towardsdatascience.com/understanding-singular-value-decomposition-and-its-application-in-data-science-388a54be95d
U, S, V = np.linalg.svd(A)

U

array([[-0.53274261, -0.84627732],
       [-0.84627732,  0.53274261]])

In [ ]:
A = np.arange(9).reshape(3,3)

#Find eigenvalues on square matrix
np.linalg.eig(A)

(array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16]),
 array([[ 0.16476382,  0.79969966,  0.40824829],
        [ 0.50577448,  0.10420579, -0.81649658],
        [ 0.84678513, -0.59128809,  0.40824829]]))

### Common Calculations in Data Science

This section shows us how to: 

1. Flatten a matrix
2. Reshape the matrix
3. Change the type of elements
4. Concatenate 2 matrices
5. Create a copy of A with a specified range
6. Add the elements in the same rows or columns to create a new vector
7. Shuffle the elements in the array

In [ ]:
#Flatten a matrix by row
A.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#Flatten a matrix by column
A = A.flatten(order='F')
A

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [ ]:
#Reshape the flattened matrix
A = A.reshape((3,3))
A

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
#Change the type of the elements
A.astype(float)

array([[0., 3., 6.],
       [1., 4., 7.],
       [2., 5., 8.]])

In [ ]:
#Create a copy of A
newA = np.copy(A)
newA

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
B.reshape(2,3)

array([[1., 3., 4.],
       [3., 2., 1.]])

In [ ]:
#Add the matrix B to columns of matrix A 
np.concatenate([A,B], axis = 0)

array([[0., 3., 6.],
       [1., 4., 7.],
       [2., 5., 8.],
       [1., 3., 4.],
       [3., 2., 1.]])

In [ ]:
#Create a copy of A with every entry in the matrix, the lowest is 0 and highest is 5
#The element that does not satisfy the condition will become the lowest or highest value
display(np.clip(A, 0.0, 5))
display(newA)

array([[0., 3., 5.],
       [1., 4., 5.],
       [2., 5., 5.]])

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
#Add the elements in the same row to create a new vector
display(A)
np.sum(A, axis = 0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

array([ 3, 12, 21])

In [ ]:
#Take the average the elements in the same row to create a new vector
np.average(A, axis = 0)

array([1., 4., 7.])

In [ ]:
x = np.arange(9).reshape(3,3); print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
np.random.shuffle(x)
x

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])